#!/usr/bin/env node
import '../src/js/core/env.js';
import { cpSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import { root } from '../src/js/core/paths.js';

const run = (file, args = []) => execFileSync(process.execPath, [join(root, file), ...args], {
  cwd: root, stdio: 'inherit', env: process.env,
});
run('node_modules/webpack-cli/bin/cli.js', ['--config', 'webpack.config.js']);
run('sh/twig_setup');
run('node_modules/node-gyp/bin/node-gyp.js', ['configure']);
run('node_modules/node-gyp/bin/node-gyp.js', ['build']);

mkdirSync(join(root, 'build/assets'), { recursive: true });
cpSync(join(root, 'node_modules/@fortawesome/fontawesome-free/webfonts'), join(root, 'build/assets/webfonts'), { recursive: true });
